### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output/blocks_gr/domain.pddl'

### ISSUE THREAD

**Issue by charonah** [leonardoamado/gr_from_demonstration#4]
Sorry for bother:
When I run `python experiments.py`  inside the src/ folder. The above error occurs. There seems to be a missing gr_dataset.
Looking forward to your detailed answers and demonstrations.
Thanks a lot !!!

**Comment by leonardoamado** [comment]
Included the dataset, should be fixed now.

**Comment by charonah** [comment]
great! Thanks a lot!!!

**Comment by charonah** [comment]
Can you provide a tutorial on how to generate dataset? Since  when I run `src/pddl_to_gym.py`, the error`ImportError: cannot import name 'wrap_goal_literal'` occurs. Appreciate sincerely !

**Comment by leonardoamado** [comment]
I will look into it, currently that file does not have a main function implemented. Basically to convert to gym, you must add some lines in the domain file and the problem file. The method `complete_domain` and `complete_problem` are responsible for that. The method `gr_to_gym` do these steps in a directory, following the directory format of goal recognition problems introduced by Ramirez and Geffener (2009).
